export const CLOUD_THEME_APPEARANCE = "CLOUD_THEME_APPEARANCE";

export const CLOUD_THEME_PRIMARY_COLOR = "CLOUD_THEME_PRIMARY_COLOR";

export const CLOUD_THEME_NEUTRAL_COLOR = "CLOUD_THEME_NEUTRAL_COLOR";
